// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {ERC4626} from "solmate/src/tokens/ERC4626.sol";
import {ERC20} from "solmate/src/tokens/ERC20.sol";
import {SafeTransferLib} from "solmate/src/utils/SafeTransferLib.sol";

/// @title FluxVault
/// @notice Confidential Yield Vault for Flux Finance
contract FluxVault is ERC4626 {
    using SafeTransferLib for ERC20;

    /// @notice Address of the TEE Attestation Verifier
    address public immutable attestationVerifier;

    /// @notice Error thrown when an invalid TEE attestation is provided
    error InvalidAttestation();

    constructor(
        ERC20 _asset,
        string memory _name,
        string memory _symbol,
        address _attestationVerifier
    ) ERC4626(_asset, _name, _symbol) {
        attestationVerifier = _attestationVerifier;
    }

    /// @notice Deposits assets securely verified by the Vela TEE enclave
    /// @param assets The amount of underlying assets to deposit
    /// @param receiver The address to receive shares
    /// @param attestation Cryptographic attestation generated by the Vela TEE Enclave
    function shieldedDeposit(uint256 assets, address receiver, bytes calldata attestation) external returns (uint256 shares) {
        if (!verifyAttestation(attestation)) {
            revert InvalidAttestation();
        }

        // Standard ERC4626 deposit logic after TEE verification
        shares = deposit(assets, receiver);
    }

    function totalAssets() public view override returns (uint256) {
        return asset.balanceOf(address(this));
    }

    function getAPY() public pure returns (uint256) {
        return 1240; // 12.4% (e.g. 12.4% * 100 = 1240)
    }

    /// @notice Internal logic to verify the TEE signature against the known Enclave identity
    /// @param attestation The bytes payload containing the proof
    function verifyAttestation(bytes calldata attestation) internal view returns (bool) {
        // MOCK VALIDATION: In production, this would call the `attestationVerifier` contract
        // passing the payload to verify the signature comes from a trusted Vela Enclave running
        // the correct expected hash (MRENCLAVE).
        if (attestation.length == 0) return false;
        
        return true; 
    }
}
